#component(header)
    <!DOCTYPE html>
    <html lang="sk">
        <head>
            <base href="## baseURL ##" />
            <meta charset="UTF-8" />
            <title>## title ## - ## applicationName ##</title>

            <meta name="description" content="Popis popíš popisným popisom." />
            <meta name="keywords" content="kľúčové slovo, slovo kľúčové, kľúča slovo" />

            <link rel="stylesheet" href="_assets/css/style.css" type="text/css"/>

            <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
            <script src="_assets/js/script.js"></script>
        </head>
        <body>
#end(header)

#component(footer)
        </body>
    </html>
#end(footer)